### ISSUE TITLE
Does not detect repos

### ISSUE THREAD

**Issue by will-stone** [mohitsinghs/vscode-repo#5] opened 2022-08-11 14:11 UTC
<img width="407" alt="image" src="https://user-images.githubusercontent.com/654103/184153160-f456445a-10ca-44e4-8c03-2ddf68760643.png">

Let me know if there's any debug info I can send

**Comment by mohitsinghs** [comment] 2022-08-11 14:35
Seems strange to me. This should ideally render instantly. This extension gets it's data from [repo](https://github.com/mohitsinghs/repo) binary which is bundled in the extension. There is a bug in case of M1 where this returns nothing and I would like to debug that.

Can we check the output of
- `repo cmp -f`
- `repo cmp -t`
- `repo cmp -j`


This binary should be [here](https://github.com/mohitsinghs/repo/releases/tag/0.5.1)

I've around 40 repos in several levels and it takes under 100ms, so something is clearly off above.

![bench](https://user-images.githubusercontent.com/4941333/184158120-4061d80a-d4e4-47af-8d52-7e95692878c8.png)

**Comment by will-stone** [comment] 2022-08-12 08:21
Those commands work when run from iTerm.app, but hang when run from VSCode's terminal, and interestingly also hang when run from Terminal.app. I cannot paste the output as this is my work laptop and I may inadvertently publish confidential information (project names etc.), but iTerm.app does indeed print a list of git repos in my home directory.

- macOS: 12.5
- CPU arch: intel

**Comment by mohitsinghs** [comment] 2022-08-12 08:59
Thanks for the info.
> I cannot paste the output as this is my work laptop and I may inadvertently publish confidential information (project names etc.)

Those commands were for you to check the output if we are getting repos, so sharing is not needed at all. Looks like we have the issue in the binary itself. something platform or shell specific.

> Those commands work when run from iTerm.app, but hang when run from VSCode's terminal.
I guess something is wrong with the default terminal/shell. 

- Does iTerm and Terminal.app are having same shell ?
- Is there any panic or it just hangs ?

Guess it's time add debug mode in binary. I'll make sure it doesn't print any sensitive info.

**Comment by will-stone** [comment] 2022-08-12 09:30
Oh yes, forgot to mention, I use `fish` shell throughout.

It just hangs, nothing shown after waiting 30s or so (I just cancel it after that).

Happy to help 🙂 Although I'm a JS/TS bod only, so unfortunately I can't help with any Rust code.

**Comment by mohitsinghs** [comment] 2022-08-12 15:09
I'll handle the rust 😁. Got some debug builds ready for you [here](https://github.com/mohitsinghs/repo/releases/tag/debug-1). Let's start with `repo cmp -f`. In order to print info we require you'll need to run `INFO=1 repo cmp -f`

Try this in iTerm, Terminal.app and VSCode Terminal. This should tell us where is it getting stuck.

**Comment by mohitsinghs** [comment] 2022-08-17 13:08
Published v0.4.1 of extension. There was a bug in binary which caused early exit on traversal. This was affect macOS. While I'm still not sure about your issue, you may give it a try.

**Comment by mohitsinghs** [comment] 2022-08-17 13:12
Published v0.4.1 of extension. It fixes a bug in binary which caused early exit on traversal. This was affecting macOS.

I'm still not sure about root cause of your issue because I tested it in M1 and Intel Macs and it worked fine expect traversal bug. You may give this release a try though.

**Comment by mohitsinghs** [comment] 2022-08-23 04:02
Closing this as of now since I am unable to reproduce this and after several fixes, the extension seems to work fine for others on Intel and M1 Macs. Feel free to reopen when we have more info on this.

**Closed as completed by mohitsinghs** 2022-08-23 04:02 UTC

**Comment by will-stone** [comment] 2022-08-24 08:12
Hi @mohitsinghs Sorry for not getting back to you sooner. Yes, that's working now! Thank you.

**Comment by mohitsinghs** [comment] 2022-08-24 09:39
Glad that it worked. This entire time, I forgot that I have an old Macbook 😄, or else I would have fixed it sooner.
